spring:
  profiles:
    active: dev
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
feign:
  circuitbreaker:
    enabled: true
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: jctoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
server:
  port: 7772
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#替换成自己的微信appId和密钥 下面是随便输入的运行不起来
wechat:
  appId: wx299a0ab27782093h
  appSecret: 1032bbd5130ebbf6b025f7eb79911e50